# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.CharField(max_length=156, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=2048)),
                ('type', models.CharField(max_length=5, verbose_name=(('LEGE', 'Lege'), ('HG', 'Hotărâre de guvern'), ('OG', 'Ordonanță de guvern'), ('OUG', 'Ordonanță de urgență'), ('OM', 'Ordin de ministru'), ('OTHER', 'Altceva...')))),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('feedback_days', models.PositiveSmallIntegerField(null=True)),
                ('contact', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Institution')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Publication'),
        ),
        migrations.AddField(
            model_name='document',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
