# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170309_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='short_name',
        ),
        migrations.AddField(
            model_name='publication',
            name='identifier',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Publication'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.CharField(max_length=156, primary_key=True, serialize=False),
        ),
    ]
