# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170312_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='feedback_days',
            new_name='_feedback_days',
        ),
        migrations.AddField(
            model_name='institution',
            name='_feedback_days',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='max_feedback_date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 5, 7)),
            preserve_default=False,
        ),

        # TODO: update the existing data here, or squash migrations
    ]
