# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170310_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='feedback_days',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
