# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170311_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
