# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170311_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
