# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170311_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='issuer',
            new_name='institution',
        ),
    ]
